name: Run Tests
run-name: Run tests ${{ github.ref_name}}.${{ github.run_id}}-${{ github.run_number}}.${{ github.run_attempt}}
on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '5.x'
      
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Docker login
        uses: azure/cli@v2
        with:
          inlineScript: az acr login --name vars.CONTAINER_REGISTRY

      - name: Run tests using Docker
        run: >
          chmod -R 777 ${{ github.workspace }};
          docker run
          -v ${{ github.workspace }}:/app
          -w /app -e DYALOG_SERIAL=${{ secrets.DYALOG_SERIAL }}
          -e LOAD=/app/tasks/RunTests.aplf
          -e GITVERSION="${{ env.GitVersion_LegacySemVer }}"
          -e GITHUB_TOKEN="${{ github.token }}"
          -e GITHUB_REPOSITORY="${{ github.repository }}"
          -e GITHUB_SHA="${{ github.sha }}"
          ${{ vars.CONTAINER_REGISTRY }}/dyalog:v190-dotnet;
          exit $?
